/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 免鉴权。用于部署后确认服务活着，以及确认它真的连得上数据库。
         *
         *     它会实际查询一次数据库而不只是回一个常量——否则「服务活着但数据库连不上」
         *     或「迁移没跑」这类情况会被它瞒过去。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 只报状态，不报细节。这个端点公开可访问，因此它不返回行数、版本号、
         *     错误原文一类会向陌生人泄露内部情况的东西。
         * @example {
         *       "status": "ok",
         *       "database": "ok"
         *     }
         */
        Health: {
            /**
             * @description 整体状态。任何一个依赖不正常即为 degraded。
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @description 数据库是否可查询。
             * @enum {string}
             */
            database: "ok" | "error";
        };
        /**
         * @description 全站统一的错误响应体，由 platform/httpx 的 HTTPErrorHandler 产出。
         * @example {
         *       "message": "资源不存在",
         *       "request_id": "4Xq2mJ9nS1kP"
         *     }
         */
        Error: {
            /** @description 面向站主的错误说明。不包含堆栈、SQL 或内部路径。 */
            message: string;
            /** @description 本次请求的 ID，与访问日志里的同一个值，便于对照排查。 */
            request_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务与数据库都正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 服务活着，但数据库不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
