// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// Defines values for HealthDatabase.
const (
	HealthDatabaseError HealthDatabase = "error"
	HealthDatabaseOk    HealthDatabase = "ok"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case HealthDatabaseError:
		return true
	case HealthDatabaseOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Error 全站统一的错误响应体，由 platform/httpx 的 HTTPErrorHandler 产出。
//
// Example: {"message":"资源不存在","request_id":"4Xq2mJ9nS1kP"}
type Error struct {
	// Message 面向站主的错误说明。不包含堆栈、SQL 或内部路径。
	Message string `json:"message"`

	// RequestId 本次请求的 ID，与访问日志里的同一个值，便于对照排查。
	RequestId *string `json:"request_id,omitempty"`
}

// Health 只报状态，不报细节。这个端点公开可访问，因此它不返回行数、版本号、
// 错误原文一类会向陌生人泄露内部情况的东西。
//
// Example: {"database":"ok","status":"ok"}
type Health struct {
	// Database 数据库是否可查询。
	Database HealthDatabase `json:"database"`

	// Status 整体状态。任何一个依赖不正常即为 degraded。
	Status HealthStatus `json:"status"`
}

// HealthDatabase 数据库是否可查询。
type HealthDatabase string

// HealthStatus 整体状态。任何一个依赖不正常即为 degraded。
type HealthStatus string
