name: build & deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev]
  workflow_dispatch:   # 可选，允许手动触发

env:
  VPS_HOST: 176.124.212.32
  VPS_USER: root
  COREPACK_ENABLE_DOWNLOAD_PROMPT: 0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4